# Generated by Django 4.2.23 on 2025-12-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_fix_tenantuser_fk'),
        ('seo', '0007_repurposejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeZoneIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('idea_type', models.CharField(choices=[('microtool', 'Microtool'), ('campaign', 'Campaign'), ('content', 'Content')], default='microtool', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255)),
                ('effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('launched', 'Launched'), ('archived', 'Archived')], default='open', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_zone_ideas', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AeoChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('poor', 'Poor'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeo_checklist', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
