from django.urls import path

from . import api_views as views

urlpatterns = [
    path("features/", views.feature_index, name="feature-index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("leads/", views.leads, name="leads"),
    path("aeo/readiness/", views.aeo_readiness, name="aeo-readiness"),
    path("aso/apps/", views.aso_apps, name="aso-apps"),
    path("aso/apps/<int:app_id>/", views.aso_app_detail, name="aso-app-detail"),
    path("aso/keywords/", views.aso_keywords, name="aso-keywords"),
    path("aso/listings/", views.aso_listings, name="aso-listings"),
    path("free-zone/", views.free_zone, name="free-zone"),
    path("marketplace/products/", views.marketplace_products, name="marketplace-products"),
    path(
        "marketplace/products/<int:product_id>/",
        views.marketplace_product_detail,
        name="marketplace-product-detail",
    ),
    path("marketplace/reviews/", views.marketplace_reviews, name="marketplace-reviews"),
    path(
        "marketplace/reviews/<int:review_id>/",
        views.marketplace_review_detail,
        name="marketplace-review-detail",
    ),
    path("marketplace/orders/", views.marketplace_orders, name="marketplace-orders"),
    path("marketplace/saved/", views.marketplace_saved_products, name="marketplace-saved"),
    path(
        "marketplace/conversations/",
        views.marketplace_conversations,
        name="marketplace-conversations",
    ),
    path("marketplace/messages/", views.marketplace_messages, name="marketplace-messages"),
    path("analytics/sites/", views.analytics_sites, name="analytics-sites"),
    path("analytics/sites/<int:site_id>/", views.analytics_site_detail, name="analytics-site-detail"),
    path("analytics/pageviews/", views.analytics_pageviews, name="analytics-pageviews"),
    path("multilingual/summary/", views.multilingual_summary, name="multilingual-summary"),
    path("tenants/summary/", views.tenant_summary, name="tenants-summary"),
    path("tenants/<int:tenant_id>/members/", views.tenant_members, name="tenant-members"),
    path("tenants/integrations/", views.tenant_integrations, name="tenant-integrations"),
    path("seo/sites/", views.seo_sites, name="seo-sites"),
    path("seo/sites/<int:site_id>/", views.seo_site_detail, name="seo-site-detail"),
    path("seo/keywords/", views.seo_keyword_clusters, name="seo-keywords"),
    path("seo/content/", views.seo_content_items, name="seo-content"),
    path("seo/faqs/", views.seo_faqs, name="seo-faqs"),
    path("seo/pr-pitches/", views.press_pitches, name="press-pitches"),
    path("seo/repurpose/", views.seo_repurpose, name="seo-repurpose"),
    path("social/accounts/", views.social_accounts, name="social-accounts"),
    path("social/posts/", views.social_posts, name="social-posts"),
    path("social/conversations/", views.social_conversations, name="social-conversations"),
    path("social/comments/", views.social_comments, name="social-comments"),
    path("social/engagement/", views.social_engagement, name="social-engagement"),
    path("social/messages/", views.social_messages, name="social-messages"),
    path("social/schedule/", views.social_schedule, name="social-schedule"),
    path("email/lists/", views.email_lists, name="email-lists"),
    path("email/templates/", views.email_templates, name="email-templates"),
    path("email/flows/", views.email_flows, name="email-flows"),
    path("email/contacts/", views.email_contacts, name="email-contacts"),
    path("email/sends/", views.email_sends, name="email-sends"),
    path("email/campaigns/", views.email_campaigns, name="email-campaigns"),
    path("email/sms/", views.sms_messages, name="sms-messages"),
    path("report/dashboard/", views.dashboard_report, name="dashboard-report"),
]
