# Generated by Django 4.2.26 on 2025-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applisting',
            name='bundle_id',
            field=models.CharField(help_text='Bundle or package identifier', max_length=200),
        ),
    ]
