# Generated by Django 4.2.26 on 2025-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applisting',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applisting',
            name='primary_keyword',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
