# Generated by Django 4.2.26 on 2025-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_site_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='is_indexable',
            field=models.BooleanField(default=True, help_text='Should search engines index this page?'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords used for meta tags.'),
        ),
    ]
